Added New login system and a sample-config
CollectiveIndustries/StarfleetDelta pull request #68
Opened 2018-04-08 20:59 UTC by hollowomnicron

Created a Better Login System and a new sample-config.php

2018-04-21 20:59 UTC, hollowomnicron commented
If you want any other features in the login system, send me a email at hollow@omega-grid.org

2018-04-24 20:31 UTC, Morketh commented
I do apologize for the long delay on merging the new login system I've been called away to deal with some other tech related problems at work thats been absorbing all of my time as of late. i did manage to get the repository downloaded and the code cleaned up (just formatting and bracket structure stuff really). However once the LAMP stack on my development box was installed I've been getting 500 error on the webpage.

Ive coppied the sample config provided and filled out the required details however i still need to set up the MySQL user for the web portal to work correctly. If we could add a failsafe to notify the user/admin that DB is not configured correctly that would be much better then a blank 500 error.

2018-04-24 23:40 UTC, hollowomnicron commented
I will create a error page

2018-04-24 23:46 UTC, hollowomnicron commented
@Morketh  Would you rather the error be returned using a function or .htaccess

2018-04-25 00:21 UTC, Morketh commented
I think either or would be fine, however i dont think the .htaccess method allows for CSS layouts. Its just eye candy and unnecessary but would be nicer and friendlier for the user in the long run.

EDIT: I retract my comment as you already posted those changes :)

2018-04-25 00:22 UTC, IAmNolanPerry commented
I just added a error page to the pull request, the layout uses Google's Error Page, and the code is from a repo i have https://github.com/hollowomnicron/errorpages 

You can configure it to accept errors other than 404 and 500

2018-04-25 00:26 UTC, hollowomnicron commented
Also, When you get a chance i would like to talk inworld

2018-04-25 00:52 UTC, Morketh commented
Of course. Soonest ill be able to get in world will be most likely the 26th.

2018-04-25 00:54 UTC, hollowomnicron commented
@Morketh  do you have IM to email enabled on your account?

2018-10-26 12:31 UTC, hollowomnicron commented
@Morketh Have you done the review yet? I would like to be able to delete the fork

2018-10-30 07:48 UTC, Morketh commented
Not yet. I just got all my development tools all set up. I will mark this as a top priority, currently out of town for a funeral and as such I'm on mobile for a few days. If you still want to chat in world let me know so we can schedule a time and place.

2018-10-30 10:34 UTC, Morketh requested changes
Overall code looks good. Some minor tweaking was required to get it to function, see notes. Login screen is simple and clean :) however even with an account i am unable to login properly. Its a great start. If these issues can be resolved i would love to be able to merge this. Thank-you again for the contributions.

2018-10-30 10:34 UTC, Morketh commented on php/login.php
> +                    $username_err = 'No account found with that username.';
L#56-61 Potential security flaw. An attacker could easily guess if a username is already on file simply by checking against the error message this could lead to a highly probable success of an attack on the site.

2018-10-30 10:34 UTC, Morketh commented on php/style.css
> +
``self._note(ask Evo for png files for backgrounds and logos):``

2018-10-30 10:34 UTC, Morketh commented on php/login.php
> +                <input type="password" name="password" class="form-control">
As far as i can tell there seems to be no encryption on the password during the login process. ``input type="password"`` only _masks_ the password from view.

2018-10-30 10:34 UTC, Morketh commented on php/login.php
> +        $password = trim($_POST['password']);
password is only trimmed at this point with no added encryption.

2018-10-30 10:34 UTC, Morketh commented on php/login.php
> +                        if($password == $hashed_password){
And here the plain text password is being compared with a hashed password from the SQL storage.

From python/installer.py L26: ``sql = "INSERT INTO `accounts` (`username`, `password`, `db_privlage_level`) VALUES (%s, SHA2(%s, 512), 3)"``

Also in the Mysql/install.sql L31: `` `password` char(106) DEFAULT NULL COMMENT '128 char long sha512 hash'``

2018-10-30 10:34 UTC, Morketh commented on php/sample-config.php
> +if(mysqli_connect_errno()) { die('Databse Connection Error - ' . mysqli_connect_error())
Missing a ``; }`` brace here on the end of the line.
```bash
admiral@StarFleetDelta:/var/www/html$ php ./login.php
PHP Parse error:  syntax error, unexpected end of file in /var/www/html/config.php on line 11```

2018-10-30 10:34 UTC, Morketh commented on php/login.php
> +                            header("location: welcome.php");
Verified password issue with Firefox, Explorer, Edge (unable to test with Chrome, and Safari however I'm sure results will be the same)
No error message is being returned and password is not being accepted. See following image: ![Screen capture](https://i.imgur.com/aniXmu0.png)

2018-12-03 17:45 UTC, Morketh commented
@hollowomnicron have you had a chance to look over the requested changes? id like to be able to merge this branch and clean up the repository. Let me know if/when you get a chance to look this over.
Morketh

2018-12-03 18:12 UTC, hollowomnicron commented
I can not do the changes, It worked on my end and I give it as is, I set it to allow edits from maintainers, I no longer do php programmng, i now focus on making Virtual OpenSim Campuses for Schools

2018-12-03 20:11 UTC, MyNameIsKodos commented
> I can not do the changes, It worked on my end and I give it as is, I set it to allow edits from maintainers, I no longer do php programmng, i now focus on making Virtual OpenSim Campuses for Schools

If you're not willing to support this further, then I am going to close this PR without merge. If it doesn't work on our end, we can't know it'll work for the end user.

2018-12-03 20:11 UTC, closed without merging